plants:
  demo-data-file: "classpath:demo-data/import.csv"
  demo-data-images: "classpath:demo-data"
  demo-data-import-mode: import_once
micronaut:
  application:
    name: micronautPlants
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pembana
    driverClassName: org.postgresql.Driver
    username: pembana
    password: pembana
    schema-generate: NONE
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: false
jackson:
  serialization:
    INDENT_OUTPUT: true